FROM mcr.microsoft.com/dotnet/core/sdk:3.1

ARG LBHPACKAGESTOKEN
ENV LBHPACKAGESTOKEN=$LBHPACKAGESTOKEN
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY /NuGet.Config /root/.nuget/NuGet/NuGet.Config
RUN dotnet restore

# Copy everything else and build
COPY ./FinanceServicesApi ./
RUN dotnet build -c Release -o out ./FinanceServicesApi.csproj
RUN dotnet publish -c Release -o out ./FinanceServicesApi.csproj

EXPOSE ${PORT:-3000}
CMD ASPNETCORE_URLS=http://+:${PORT:-3000} dotnet ./out/FinanceServicesApi.dll
