service: finance-services-api
provider:
  name: aws
  runtime: dotnetcore3.1
  memorySize: 2048
  tracing:
    lambda: true
    apiGateway: true
  vpc: ${self:custom.vpc.${opt:stage}}
  stage: ${opt:stage}
  account: ${opt:account}
  region: eu-west-2

package:
# TODO: Rename zipfile in build.sh and build.cmd to match this
  artifact: ./bin/release/netcoreapp3.1/finance-services-api.zip

functions:
  FinanceServicesApi:
    name: ${self:service}-${self:provider.stage}
    handler: FinanceServicesApi::FinanceServicesApi.LambdaEntryPoint::FunctionHandlerAsync
    role: lambdaExecutionRole
    environment:
      ACCOUNT_API_URL: ${ssm:/housing-finance/${self:provider.stage}/account-api-url}
      ACCOUNT_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/account-api-token}
      TRANSACTION_API_URL: ${ssm:/housing-finance/${self:provider.stage}/financial-transactions-api-url}
      TRANSACTION_API_KEY: ${ssm:/housing-finance/${self:provider.stage}/financial-transactions-api-key}
      TENURE_API_URL: ${ssm:/housing-finance/${self:provider.stage}/tenure-api-url}
      TENURE_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/tenure-api-token}
      FINANCIAL_SUMMARY_API_URL: ${ssm:/housing-finance/${self:provider.stage}/financial-summary-api-url}
      FINANCIAL_SUMMARY_API_KEY: ${ssm:/housing-finance/${self:provider.stage}/financial-summary-api-key}
      # FINANCIAL_SUMMARY_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/tenure-api-token}
      CHARGE_API_URL: ${ssm:/housing-finance/${self:provider.stage}/charge-api-url}
      CHARGE_API_KEY: ${ssm:/housing-finance/${self:provider.stage}/charge-api-key}
      #CHARGE_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/charge-api-token}
      CONTACT_DETAILS_API_URL: ${ssm:/housing-tl/${self:provider.stage}/contact-details-api-url-v2}
      CONTACT_DETAILS_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/contact-details-api-token}
      #CHARGE_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/charge-api-token}
      ASSET_INFORMATION_API_URL: ${ssm:/housing-finance/${self:provider.stage}/asset-information-api-url}
      ASSET_INFORMATION_API_TOKEN: ${ssm:/housing-finance/${self:provider.stage}/asset-information-api-token}
      # ${ssm:/repairs-api/${self:provider.stage}/asset-information-api-token}
      PERSON_API_URL: ${ssm:/housing-tl/${self:provider.stage}/person-api-url}
      PERSON_API_TOKEN: ${ssm:/housing-tl/${self:provider.stage}/person-api-token}
      SEARCH_API_URL: ${ssm:/housing-tl/${self:provider.stage}/search-api-url}
      SEARCH_API_AUTH_KEY: ${ssm:/housing-tl/${self:provider.stage}/search-api-auth-key}
      REQUIRED_GOOGL_GROUPS: ${ssm:/housing-finance/${self:provider.stage}/authorization/required-google-groups}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          authorizer:
            arn: ${ssm:/api-authenticator/${self:provider.stage}/arn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            managedExternally: true
          cors:
            origin: '*'
            headers:
              - Content-Type
              - If-Match
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /swagger/{proxy+}
          method: GET
          private: false
resources:
  Resources:
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /${self:service}/${self:provider.stage}/
        RoleName: ${self:service}-lambdaExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        Policies:
          - PolicyName: manageLogs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
          - PolicyName: lambdaInvocation
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"
custom:
  vpc:
    development:
      subnetIds:
        - subnet-0deabb5d8fb9c3446
        - subnet-000b89c249f12a8ad
    staging:
      subnetIds:
        - subnet-06d3de1bd9181b0d7
        - subnet-0ed7d7713d1127656
    production:
      subnetIds:
        - subnet-01d3657f97a243261
        - subnet-0b7b8fea07efabf34
